// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQmoj7t46Em2h7I8ZDPbOHYlUoz1Zq6DU',
    appId: '1:759973523581:web:ec7c07e1eebff721e48114',
    messagingSenderId: '759973523581',
    projectId: 'fir-db-987ae',
    authDomain: 'fir-db-987ae.firebaseapp.com',
    storageBucket: 'fir-db-987ae.firebasestorage.app',
    measurementId: 'G-EHYLKY68VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCldnDwwGAtxZKvaeafHsw-7FnqZ2lvkDI',
    appId: '1:759973523581:android:8b7088cafadad202e48114',
    messagingSenderId: '759973523581',
    projectId: 'fir-db-987ae',
    storageBucket: 'fir-db-987ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2EWJsWCK-heQGhpbBipCnom5RWTjNGSI',
    appId: '1:759973523581:ios:d826010ff13fbd68e48114',
    messagingSenderId: '759973523581',
    projectId: 'fir-db-987ae',
    storageBucket: 'fir-db-987ae.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDatabaseAssignment',
  );
}
