// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkUrGJF9AVpv7nX8A0feGGCI16QeyQOa8',
    appId: '1:1070245686260:web:d58f7f10a62286481327a1',
    messagingSenderId: '1070245686260',
    projectId: 'fir-assignment-2a527',
    authDomain: 'fir-assignment-2a527.firebaseapp.com',
    storageBucket: 'fir-assignment-2a527.firebasestorage.app',
    measurementId: 'G-FJQS73ZGN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZmUm9zRlce93QfxXAKZknql3QA5yuM_8',
    appId: '1:1070245686260:android:ab2c9b4637127efd1327a1',
    messagingSenderId: '1070245686260',
    projectId: 'fir-assignment-2a527',
    storageBucket: 'fir-assignment-2a527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyJeYb82rUJe1rfIzzJrSj8DY87e5YaOg',
    appId: '1:1070245686260:ios:c3fd73f67542db701327a1',
    messagingSenderId: '1070245686260',
    projectId: 'fir-assignment-2a527',
    storageBucket: 'fir-assignment-2a527.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDatabaseAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkUrGJF9AVpv7nX8A0feGGCI16QeyQOa8',
    appId: '1:1070245686260:web:b88f74235adeabe01327a1',
    messagingSenderId: '1070245686260',
    projectId: 'fir-assignment-2a527',
    authDomain: 'fir-assignment-2a527.firebaseapp.com',
    storageBucket: 'fir-assignment-2a527.firebasestorage.app',
    measurementId: 'G-HG9JYL3P2X',
  );
}
